version: '2'
services:
  proxy:
    image: nginx:1.23.1
    volumes:
      - type: bind
        source: ./default.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    networks:
      - frontend
    links:
      - "web:app"
    ports:
      - 80:80
    depends_on:
      - web
  
  web:
    image: nicopaez/jobvacancy-ruby:1.3.0
    links:
      - db
    networks:
      - backend
      - frontend
    environment:
      PORT: "3000"
      RACK_ENV: "production"
      DATABASE_URL: "postgres://postgres:Passw0rd!@db:5432/postgres"
    depends_on:
      - db
  db:
    image: postgres:14.4-alpine
    networks:
      - backend
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/pass
    secrets:
      - pass

secrets:
  pass:
    file: secrets/pass

networks:
  frontend:
    name: frontend
  backend:
    name: backend
