version: '3.8' 
services:
  backend_1:
    image: nicopaez/password-api:2.1.0
    expose:
      - 3000

  backend_2:
    image: nicopaez/password-api:2.1.0
    expose:
      - 3000
  lb:
    image: nginx:1.23.1
    volumes:
      - type: bind
        source: ./lb/nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
    
    links:
      - "backend_1:app1"
      - "backend_2:app2"
    ports:
      - 80:80
    depends_on:
      - backend_1
      - backend_2