apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-exec
spec:
  containers:
    - name: pingapp
      image: nicopaez/password-api:1.5.0-java
      livenessProbe:
        httpGet:
            path: /actuator/health
            port: 8080
        initialDelaySeconds: 15
        periodSeconds: 5
