apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingapp
  labels:
    app: pingapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pingapp
  template:
    metadata:
      labels:
        app: pingapp
    spec:
      containers:
      - name: pingapp
        image: nicopaez/pingapp:4.0.0
        ports:
        - containerPort: 4567
        livenessProbe:
          httpGet:
              path: /is-alive
              port: 4567
          initialDelaySeconds: 15
          periodSeconds: 10