FROM registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift:1.12-1.1661378017

ENV JAVA_APP_JAR=passwordapi.jar
ENV JAVA_APP_DIR=/deployments

COPY passwordapi.jar /deployments/passwordapi.jar
